Added GitHub Login
amy-lei/dashboard pull request #10
Opened 2020-07-14 20:42 UTC by roeeyn

Added GitHub Login

2020-07-14 21:50 UTC, amy-lei commented on client/package.json
> +    "styled-components": "^5.1.1"
This is my first time using styled-components, but will it limiting? I guess my main concern is just variables. Im currently using sass for the card components, and Ive added a lot of variables for consistent coloring/sizing.

2020-07-14 21:51 UTC, amy-lei commented on client/src/components/GitHubHome.js
> +        <button onClick={()=> handleLogout()}>Logout</button>
i think since we're not passing any args, it can just be `onClick={handleLogout}`

2020-07-14 22:02 UTC, amy-lei requested changes
This is great! I left a comment about using `styled-components` in general, and one for a minor change.

I think moving forward, we also would populate the DB with the user if this is their first time logging in, otherwise, get the user data from the DB and return it as well. Maybe that can be a separate task and a separate PR since this is good work!

2020-07-15 02:21 UTC, amy-lei approved these changes

2020-07-15 02:22 UTC, amy-lei commented
LGTM now! As i mentioned above, we'll need to create a User instance and fetch user data & posts, but i think that can be for another PR :)

2020-07-15 17:38 UTC, yahengsu commented
looks good to me, but can we move the `.css` files out to a `styles/` folder instead of keeping them in `components/`?

2020-07-15 17:45 UTC, rch-liu commented
LGTM 👍

2020-07-15 18:12 UTC, merged