Added add post feature
amy-lei/dashboard pull request #25
Opened 2020-07-16 05:49 UTC by rch-liu

This sets up the UI for adding posts, YOU CANNOT ADD A POST YET (no data). 

Clicking "add post" will open a dropdown menu where users have three options so far:
- make a general post
- make a github issue post
- make a github PR post

I'm going to work on linking backend to frontend tomorrw, and ideally improving code quality!

2020-07-16 15:09 UTC, amy-lei requested changes
I left a comment on the libraries, but I think we should get the others opinion on it or discuss it during the call. Some other thoughts I had:
1. I think a cleaner way to approach this is to have one state for opening/closing the modal `openModal` and one for which form type `formType`. This way rather than rendering 3 different forms and opening and closing each conditionally, the flow can be like this: user selects a type -> type gets set into state and modal is opened -> when rendering modal, use switch or if statements to determine the contents of the modal.  
2. We can also differ the forms. I think thats the benefit of having different post types. (e.g. with youtube videos, it's much easier to simply input the link than manually input the title, desc. with github, it's simpler to input the repo, the issue # or PR#, or the org). To be able to store the info in a state, maybe have an object instead of a separate state for title input and body input. e.g. (value = {link} or value = {title, description, link}). And because we keep track of the type, we don't have to worry about an AttributeError.  To flesh out the different types, I was thinking this:
### Youtube Videos:
```
value = {
url: String
}
```
### Github
```
value: {
  repo: String,
  number: Int,
  org: String,
  isIssue: Bool
}
```

### Note
```
value = {
  title: String
  description: String
  url: String
}
```

But this can be discussed with the others/in a call

2020-07-16 15:09 UTC, amy-lei commented on client/src/components/AddForm.js
> +import { TextArea , TextInput } from '@thumbtack/thumbprint-react';
I think it'd be best to narrow it to <= 2 libraries. I personally hold a grudge against bootstrap lol but it does offer modals and forms. So if we had to keep some, I'd go for react-bootstrap and react-hook-form (they claim to help with performance since they cut down on rerenders).

(Side note: I'm anti bootstrap just bc it grew so popular at some point that every site looked the same lol. And i end up having to override everything in my own css using `!important` so it usually ends up more work than its worth. Thats why I create my own styles)

2020-07-16 16:47 UTC, rch-liu commented on client/src/components/AddForm.js
> +import { TextArea , TextInput } from '@thumbtack/thumbprint-react';
Sorry this PR wasn't ready for for review yet I should have made it a draft PR 😅. I agree this needs to be much cleaner than its current state atm, I'm not too familiar with frontend tools and best practices so I was mostly re-using code from external sources. I'm going to try to make this cleaner today

2020-07-17 01:53 UTC, amy-lei approved these changes

2020-07-17 02:02 UTC, merged